#-------------------------------
# General Site Settings
title: Minas Karamanis
#logo: logo.svg # You can add own logo.
description: PhD Student in Cosmology


#-------------------------------
# Author Settings
author:
  name: Minas Karamanis
  image: photo.jpg
  say-hello: Hello, I’m <strong>Minas Karamanis</strong>
  bio: I'm an PhD student in Astrophysics at University of Edinburgh. I'm interested in Cosmology, the Large-Scale Structure of the Universe, Astrostatistics, Machine Learning and Bayesian Inference.


#-------------------------------
# Contact links
twitter: https://twitter.com/MinasKaramanis # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: minaskar # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e